name: media_player
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  on_audio_query: ^2.9.0
  on_audio_query_android_v1_8: ^1.1.1
  photo_manager: ^3.7.1
  shared_preferences:
  just_audio: ^0.10.4
  photo_view: ^0.15.0
  video_player: ^2.10.0
  chewie: ^1.12.1
  just_audio_background: ^0.0.1-beta.17

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

